
#---------------------------
# 首页
# Index Page
#---------------------------
index:
  banner_img: https://cdn.jsdelivr.net/gh/pingfan443/blog-imgs/imgs/20200715162704.jpg  # 首页 Banner 头图，以下相同
  banner_img_height: 100  # 头图高度，屏幕百分比，available: 0 - 100
  banner_mask_alpha: 0.3  # 头图黑色蒙版的透明度，available: 0 - 1.0， 0 是完全透明（无蒙版），1 是完全不透明
  post_default_img: '' # 默认的文章封面图，当没有指定 index_img 时会使用该图片，若都为空则不显示任何图片
  slogan:  # 首页副标题的独立设置
    enable: true  # 为 false 则不显示任何内容
    text: '发光不是太阳的权利，你也可以'  # 为空则按 hexo config.subtitle 显示
    # text: '看到这些字了吗，点我！点我！点我！'
  auto_excerpt:
    enable: true
  post_url_target: _self  # available: _blank | _self
  post_meta: # 是否显示文章信息（时间、分类、标签）
    date: true
    category: true
    tag: true

# 通过 hexo new page 命令创建的页面
# Custom Page
page:
  banner_img: /img/default.png
  banner_img_height: 60  # available: 0 - 100
  banner_mask_alpha: 0.3  # available: 0 - 1.0



